# Generated by Django 5.2.7 on 2025-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='carrier_name',
            field=models.CharField(default='Carrier', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_name',
            field=models.CharField(default='Driver', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='trailer_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='truck_number',
            field=models.CharField(default='TRUCK-001', max_length=100),
        ),
    ]
