# Generated by Django 5.2.7 on 2025-10-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0002_trip_carrier_name_trip_driver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trailer_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='truck_number',
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='carrier_name',
            field=models.CharField(blank=True, default='ELD Logistics', max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='driver_name',
            field=models.CharField(blank=True, default='Professional Driver', max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='vehicle_numbers',
            field=models.CharField(blank=True, default='TRUCK-001', max_length=200),
        ),
    ]
